### ISSUE TITLE
hosts fetch error

### ISSUE THREAD

**Issue by szkrd** [time4tea-net/py-hole#1]
I don't know much about python and I'm on an old debian (7.11), but after doing a build and a dpkg -i I tried to run the opt pyhole script, which exited with the following error:

```
Traceback (most recent call last):
  File "/opt/py-hole/py-hole", line 61, in <module>
    hosts.update(hosts_from(load_source(source)))
  File "/opt/py-hole/py-hole", line 38, in load_source
    response = requests.get(url, timeout=60)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 52, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 40, in request
    return s.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 229, in request
    r.send(prefetch=prefetch)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 631, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'mirror1.malwaredomains.com' doesn't match either of '*.gt500.org', 'gt500.org'
```

After commenting out the offending host from the list definition the next one pops up:

```
Traceback (most recent call last):
  File "/opt/py-hole/py-hole", line 61, in <module>
    hosts.update(hosts_from(load_source(source)))
  File "/opt/py-hole/py-hole", line 38, in load_source
    response = requests.get(url, timeout=60)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 52, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 40, in request
    return s.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 229, in request
    r.send(prefetch=prefetch)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 631, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'zeustracker.abuse.ch' doesn't match 'c.sni.fastly.net'
```

and after that:

```
2018-12-31 12:47:32,197 Starting new HTTPS connection (1): s3.amazonaws.com
Traceback (most recent call last):
  File "/opt/py-hole/py-hole", line 61, in <module>
    hosts.update(hosts_from(load_source(source)))
  File "/opt/py-hole/py-hole", line 40, in load_source
    return response.text.split('\n')
  File "/usr/lib/python3/dist-packages/requests/models.py", line 831, in text
    content = str(self.content, encoding, errors='replace')
TypeError: str() argument 2 must be str, not None
```

python version:

```
[root@vacak py-hole]# which python3
/usr/bin/python3
[root@vacak py-hole]# python3 --version
Python 3.2.3
```

**Comment by time4tea** [comment]
Thanks for the detailed bug report.

Hmm. I don't get that error. I suspect that your version of python is too old. Python 3.2.3 is from 2012.

I'm running python 3.5.2 and all is working.

I suspect that SSL behaviour has changed in the interim, particularly with regard to Subject Alternative Name. It can be seen that the server does in fact hand out the correct certificate, but only when using SNI extensions - which perhaps python 3.2.3 doesn't do.

e.g. get default certificate:
```
$ openssl s_client  -showcerts -connect mirror1.malwaredomains.com:443

Certificate chain
 0 s:/CN=gt500.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
```

e.g. get certificate using SNI
```
$ openssl s_client -servername mirror1.malwaredomains.com -showcerts -connect mirror1.malwaredomains.com:443

Certificate chain
 0 s:/CN=mirror1.malwaredomains.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
```

I'd be very happy to update the dependencies of the package, but for now you could update your python version.

Cheers

**Comment by szkrd** [comment]
Thank you, probably I'll do a dist upgrade soon, probably that will fix it.
